/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import login.Login;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author dilshan
 */
public class home extends javax.swing.JFrame {

    private boolean zerodisp;
    private boolean decdisp;
    private byte op;
    private double ina;
    private double inb;
    private double out;

    /**
     * Creates new form home
     */
    public home() {
        initComponents();

        jLabel10.setText(Login.jTextField1.getText());

        DateTimes();
        invoauto();
        invotridauto();
        ui1.setVisible(false);
        ui2.setVisible(false);
        try {
            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String s = sdf.format(d);
            Date d1 = sdf.parse(s);
            dtechoserdate.setDate(d1);
        } catch (Exception e) {
            e.printStackTrace();
        }

        //   btnadd.setBackground(Color.getColor("#FA5858"));
        //  btnprint.setVisible(false);

        try {

//            c1.setVisible(false);
//            c2.setVisible(false);
//            c3.setVisible(false);

            TableColumnModel tcm = tblinvo.getColumnModel();
            lblinvotbltrid.setVisible(false);

            TableColumn tc;
            for (int i = 0; i <= 0; i++) {
                tc = tcm.getColumn(0);
                tcm.removeColumn(tc);
            }


        } catch (Exception e) {
            e.printStackTrace();
        }

        btnadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnadd.setBackground(Color.GREEN);
                setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnadd.setBackground(new Color(255, 102, 102));
                setCursor(Cursor.DEFAULT_CURSOR);
            }
        });



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        time = new javax.swing.JLabel();
        nine = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        equals = new javax.swing.JButton();
        subtract = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        add = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        four = new javax.swing.JButton();
        decpoint = new javax.swing.JButton();
        display2 = new javax.swing.JTextField();
        zero = new javax.swing.JButton();
        display1 = new javax.swing.JTextField();
        three = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        negate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtinvotblmedname = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        ui1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblinvo = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        lblinvotblstockid = new javax.swing.JLabel();
        lblinvotbltrid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ui2 = new javax.swing.JLabel();
        txtdis = new javax.swing.JTextField();
        lblinvotvluprice = new javax.swing.JLabel();
        lblinvotblqty = new javax.swing.JLabel();
        txtinvotblmedid = new javax.swing.JTextField();
        txtinvocusid = new javax.swing.JTextField();
        lbltot = new javax.swing.JLabel();
        txtinvotblqty = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtinvoid = new javax.swing.JTextField();
        btnprint = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dtechoserdate = new com.toedter.calendar.JDateChooser();
        c2 = new javax.swing.JTextField();
        c3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pa = new javax.swing.JTextField();
        javax.swing.JLabel bal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Invoice");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        time.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 380, 230, 83));

        nine.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nine.setText("9");
        nine.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nine.setFocusable(false);
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });
        jPanel1.add(nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(1008, 93, 50, 50));

        eight.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        eight.setText("8");
        eight.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eight.setFocusable(false);
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });
        jPanel1.add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(952, 93, 50, 50));

        five.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        five.setText("5");
        five.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        five.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        five.setFocusable(false);
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        jPanel1.add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(952, 149, 50, 50));

        six.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        six.setText("6");
        six.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        six.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        six.setFocusable(false);
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        jPanel1.add(six, new org.netbeans.lib.awtextra.AbsoluteConstraints(1008, 149, 50, 50));

        equals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        equals.setText("=");
        equals.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        equals.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        equals.setFocusable(false);
        equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsActionPerformed(evt);
            }
        });
        jPanel1.add(equals, new org.netbeans.lib.awtextra.AbsoluteConstraints(896, 317, 162, 50));

        subtract.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        subtract.setText("-");
        subtract.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        subtract.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subtract.setFocusable(false);
        subtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractActionPerformed(evt);
            }
        });
        jPanel1.add(subtract, new org.netbeans.lib.awtextra.AbsoluteConstraints(1068, 149, 50, 50));

        reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reset.setText("C");
        reset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.setFocusable(false);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1068, 317, 50, 50));

        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setText("+");
        add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.setFocusable(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1068, 93, 50, 50));

        one.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        one.setText("1");
        one.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        one.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        one.setFocusable(false);
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        jPanel1.add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(896, 205, 50, 50));

        two.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        two.setText("2");
        two.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        two.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        two.setFocusable(false);
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        jPanel1.add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(952, 205, 50, 50));

        multiply.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        multiply.setText("*");
        multiply.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        multiply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        multiply.setFocusable(false);
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });
        jPanel1.add(multiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(1068, 205, 50, 50));

        divide.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        divide.setText("/");
        divide.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        divide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        divide.setFocusable(false);
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });
        jPanel1.add(divide, new org.netbeans.lib.awtextra.AbsoluteConstraints(1068, 261, 50, 50));

        four.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        four.setText("4");
        four.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        four.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        four.setFocusable(false);
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        jPanel1.add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(896, 149, 50, 50));

        decpoint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        decpoint.setText(".");
        decpoint.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        decpoint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        decpoint.setFocusable(false);
        decpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decpointActionPerformed(evt);
            }
        });
        jPanel1.add(decpoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(952, 261, 50, 50));

        display2.setBackground(new java.awt.Color(199, 218, 220));
        display2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        display2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        display2.setFocusable(false);
        jPanel1.add(display2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 11, 230, -1));

        zero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        zero.setText("0");
        zero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        zero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        zero.setFocusable(false);
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });
        jPanel1.add(zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(896, 261, 50, 50));

        display1.setBackground(new java.awt.Color(199, 218, 220));
        display1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        display1.setText("0");
        display1.setAutoscrolls(false);
        display1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        display1.setFocusable(false);
        jPanel1.add(display1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 52, 230, -1));

        three.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        three.setText("3");
        three.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        three.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        three.setFocusable(false);
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        jPanel1.add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(1008, 205, 50, 50));

        seven.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seven.setText("7");
        seven.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        seven.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seven.setFocusable(false);
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });
        jPanel1.add(seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(896, 93, 50, 50));

        negate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        negate.setText("±");
        negate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        negate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        negate.setFocusable(false);
        negate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negateActionPerformed(evt);
            }
        });
        jPanel1.add(negate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1008, 261, 50, 50));

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(892, 700));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Discount:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 666, -1, 26));

        txtinvotblmedname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtinvotblmedname.setText("Medicine Name");
        txtinvotblmedname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinvotblmednameActionPerformed(evt);
            }
        });
        txtinvotblmedname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtinvotblmednameFocusGained(evt);
            }
        });
        txtinvotblmedname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtinvotblmednameKeyPressed(evt);
            }
        });
        jPanel2.add(txtinvotblmedname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 120, 30));

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 19, 110, -1));

        ui1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ui1.setText("User ID:");
        jPanel2.add(ui1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 100, -1));

        tblinvo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tr ID", "Medicine ID", "Medicine Name", "Stock ID", "Unit Price", "Qty", "Amount", "Discount"
            }
        ));
        jScrollPane1.setViewportView(tblinvo);
        if (tblinvo.getColumnModel().getColumnCount() > 0) {
            tblinvo.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 872, 241));

        btnadd.setBackground(new java.awt.Color(255, 102, 102));
        btnadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnadd.setText("Add");
        btnadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnaddMouseEntered(evt);
            }
        });
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel2.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 70, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("%");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 666, -1, 26));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Net Total:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, -1, 50));

        jButton6.setText("Reset");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 19, 110, -1));

        lblinvotblstockid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblinvotblstockid.setText("Stock Id");
        lblinvotblstockid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblinvotblstockid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 120, 30));

        lblinvotbltrid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblinvotbltrid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblinvotbltrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 40, 26));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Date:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 32));

        ui2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ui2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(ui2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 186, 26));

        txtdis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtdis, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 668, 40, -1));

        lblinvotvluprice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblinvotvluprice.setText("Unit Price");
        lblinvotvluprice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblinvotvluprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 130, 30));

        lblinvotblqty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblinvotblqty.setText("Ava.Qty");
        lblinvotblqty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblinvotblqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 60, 30));

        txtinvotblmedid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtinvotblmedid.setText("Medicine ID");
        txtinvotblmedid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinvotblmedidActionPerformed(evt);
            }
        });
        txtinvotblmedid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtinvotblmedidKeyPressed(evt);
            }
        });
        jPanel2.add(txtinvotblmedid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 130, 30));

        txtinvocusid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtinvocusid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinvocusidActionPerformed(evt);
            }
        });
        jPanel2.add(txtinvocusid, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 51, 186, 27));

        lbltot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbltot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lbltot, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, 150, 27));

        txtinvotblqty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtinvotblqty.setText("Rq.Qty");
        txtinvotblqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinvotblqtyActionPerformed(evt);
            }
        });
        jPanel2.add(txtinvotblqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 60, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Invoice ID:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 90, 34));

        txtinvoid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtinvoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinvoidActionPerformed(evt);
            }
        });
        jPanel2.add(txtinvoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 186, 27));

        btnprint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnprint.setText("Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        jPanel2.add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, 150, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Customer ID:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 100, 33));

        jLabel7.setText("Please type a medicine name in the box whic appeard on the table...");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, 380, -1));

        dtechoserdate.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(dtechoserdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 186, 32));

        c2.setText("0.00");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        jPanel2.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 120, 27));

        c3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c3.setText("%");
        jPanel2.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, 29, 40));

        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 51, 222, 28));

        pa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paActionPerformed(evt);
            }
        });
        pa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paKeyReleased(evt);
            }
        });
        jPanel2.add(pa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 170, 44));

        bal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(bal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 170, 44));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("LKR");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 50, -1));

        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, 150, 50));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Discount:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, -1, 26));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("LKR");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 50, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Balance:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, 26));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Sub Total:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, -1, 26));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Paid Amount:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, 26));

        jTextField1.setText("Discount");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 50, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 884, 650));

        jButton1.setText("Rs.2000");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 580, 120, 50));

        jButton2.setText("Rs.1000");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 520, 120, 50));

        jButton4.setText("Rs.5000");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 520, 120, 50));

        jButton8.setText("Rs.500");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 580, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 650));

        jMenuBar1.setAlignmentX(2.0F);
        jMenuBar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jMenu1.setText("Transactions");
        jMenu1.setToolTipText("You can search old invoice details and create invoice by using this option");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Transaction History");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("GRN");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Employee Management");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Employee Base");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Stock Management");

        jMenuItem2.setText("Medicine Index.");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Stock Info.");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Customer Management");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem6.setText("Customer Base");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salary Management");

        jMenuItem8.setText("Create Salary Slip");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Leave");
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        jMenuItem7.setText("Quit");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
        Stockmanage sm = new Stockmanage();
        sm.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
        new med().setVisible(true);
        //setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
        transactionhistory in = new transactionhistory();
        in.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.dispose();
        grn g = new grn();
        g.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        employeeinfo emp = new employeeinfo();
        emp.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.dispose();
        details d = new details();
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        this.dispose();
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        if (!zerodisp && !decdisp) {
            display1.setText(null);
        }
        display1.setText(display1.getText() + "9");
        zerodisp = true;
    }//GEN-LAST:event_nineActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        if (!zerodisp && !decdisp) {
            display1.setText(null);
        }
        display1.setText(display1.getText() + "8");
        zerodisp = true;
    }//GEN-LAST:event_eightActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        if (!zerodisp && !decdisp) {
            display1.setText(null);
        }
        display1.setText(display1.getText() + "5");
        zerodisp = true;
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        if (!zerodisp && !decdisp) {
            display1.setText(null);
        }
        display1.setText(display1.getText() + "6");
        zerodisp = true;
    }//GEN-LAST:event_sixActionPerformed

    private void equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsActionPerformed
        inb = Double.parseDouble(String.valueOf(display1.getText()));

        if (op == 0) {
            out = inb;
            display2.setText(String.valueOf(inb));
        }

        if (op == 1) {
            out = ina + inb;
            display2.setText(display2.getText() + String.valueOf(inb));
        }

        if (op == 2) {
            out = ina - inb;
            display2.setText(display2.getText() + String.valueOf(inb));
        }

        if (op == 3) {
            out = ina * inb;
            display2.setText(display2.getText() + String.valueOf(inb));
        }

        if (op == 4) {
            out = ina / inb;
            display2.setText(display2.getText() + String.valueOf(inb));
        }

        if (op == 5) {
            out = ina * inb / 100;
            display2.setText(display2.getText() + String.valueOf(inb) + ")");
        }

        if (out > -100000000 && out < 100000000) {
            display1.setText(String.valueOf(out));
        } else {
            display1.setText("Error");
        }

        ina = 0;
        inb = 0;
        out = 0;

        op = 0;
        decdisp = false;
        zerodisp = false;
    }//GEN-LAST:event_equalsActionPerformed

    private void subtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractActionPerformed
        if (op == 0) {
            ina = Double.parseDouble(String.valueOf(display1.getText()));
        } else {
            inb = Double.parseDouble(String.valueOf(display1.getText()));
        }

        if (op == 1) {
            ina = ina + inb;
        }

        if (op == 2) {
            ina = ina - inb;
        }

        if (op == 3) {
            ina = ina * inb;
        }

        if (op == 4) {
            ina = ina / inb;
        }

        if (op == 5) {
            ina = ina * inb / 100;
        }

        display1.setText("0");
        display2.setText(String.valueOf(ina) + " - ");

        op = 2;

        decdisp = false;
        zerodisp = false;
    }//GEN-LAST:event_subtractActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        display1.setText("0");
        display2.setText(null);
        zerodisp = false;
        decdisp = false;
        ina = 0;
        inb = 0;
        out = 0;
    }//GEN-LAST:event_resetActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if (op == 0) {
            ina = Double.parseDouble(String.valueOf(display1.getText()));
        } else {
            inb = Double.parseDouble(String.valueOf(display1.getText()));
        }

        if (op == 1) {
            ina = ina + inb;
        }

        if (op == 2) {
            ina = ina - inb;
        }

        if (op == 3) {
            ina = ina * inb;
        }

        if (op == 4) {
            ina = ina / inb;
        }

        if (op == 5) {
            ina = ina * inb / 100;
        }

        display1.setText("0");
        display2.setText(String.valueOf(ina) + " + ");

        op = 1;

        decdisp = false;
        zerodisp = false;
    }//GEN-LAST:event_addActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        if (!zerodisp && !decdisp) {
            display1.setText(null);
        }
        display1.setText(display1.getText() + "1");
        zerodisp = true;
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        if (!zerodisp && !decdisp) {
            display1.setText(null);
        }
        display1.setText(display1.getText() + "2");
        zerodisp = true;
    }//GEN-LAST:event_twoActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        if (op == 0) {
            ina = Double.parseDouble(String.valueOf(display1.getText()));
        } else {
            inb = Double.parseDouble(String.valueOf(display1.getText()));
        }

        if (op == 1) {
            ina = ina + inb;
        }

        if (op == 2) {
            ina = ina - inb;
        }

        if (op == 3) {
            ina = ina * inb;
        }

        if (op == 4) {
            ina = ina / inb;
        }

        if (op == 5) {
            ina = ina * inb / 100;
        }

        display1.setText("0");
        display2.setText(String.valueOf(ina) + " * ");

        op = 3;

        decdisp = false;
        zerodisp = false;
    }//GEN-LAST:event_multiplyActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        if (op == 0) {
            ina = Double.parseDouble(String.valueOf(display1.getText()));
        } else {
            inb = Double.parseDouble(String.valueOf(display1.getText()));
        }

        if (op == 1) {
            ina = ina + inb;
        }

        if (op == 2) {
            ina = ina - inb;
        }

        if (op == 3) {
            ina = ina * inb;
        }

        if (op == 4) {
            ina = ina / inb;
        }

        if (op == 5) {
            ina = ina * inb / 100;
        }

        display1.setText("0");
        display2.setText(String.valueOf(ina) + " / ");

        op = 4;

        decdisp = false;
        zerodisp = false;
    }//GEN-LAST:event_divideActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        if (!zerodisp && !decdisp) {
            display1.setText(null);
        }
        display1.setText(display1.getText() + "4");
        zerodisp = true;
    }//GEN-LAST:event_fourActionPerformed

    private void decpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decpointActionPerformed
        if (!decdisp) {
            display1.setText(display1.getText() + ".");
            decdisp = true;
        }
    }//GEN-LAST:event_decpointActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        if (!zerodisp && !decdisp) {
            display1.setText(null);
        }
        display1.setText(display1.getText() + "0");
    }//GEN-LAST:event_zeroActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        if (!zerodisp && !decdisp) {
            display1.setText(null);
        }
        display1.setText(display1.getText() + "3");
        zerodisp = true;
    }//GEN-LAST:event_threeActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        if (!zerodisp && !decdisp) {
            display1.setText(null);
        }
        display1.setText(display1.getText() + "7");
        zerodisp = true;
    }//GEN-LAST:event_sevenActionPerformed

    private void negateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negateActionPerformed
        inb = Double.parseDouble(String.valueOf(display1.getText()));
        out = inb * -1;

        if (out > -100000000 && out < 100000000) {
            display1.setText(String.valueOf(out));
        } else {
            display1.setText("Error");
        }
        decdisp = true;
        out = 0;
    }//GEN-LAST:event_negateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {

            Statement s = database.database.pharmacy().createStatement();

            ResultSet rs1 = s.executeQuery("SELECT * FROM invoice WHERE inv-id = '" + txtinvoid.getText() + "'");
            while (rs1.next()) {
                txtinvoid.setText(rs1.getString(1));
                txtinvocusid.setText(rs1.getString(2));
                dtechoserdate.setDate(rs1.getDate(4));
                c2.setText(rs1.getString(5));
                jLabel9.setText(rs1.getString(6));
            }

            ResultSet rs2 = s.executeQuery("SELECT * FROM trans WHERE inv_id = '" + txtinvoid.getText() + "'");
            DefaultTableModel df = (DefaultTableModel) tblinvo.getModel();
            df.setRowCount(0);
            while (rs2.next()) {
                Vector v = new Vector();
                v.add(rs2.getString(1));
                v.add(rs2.getString(3));
                v.add(rs2.getString(4));
                v.add(rs2.getString(5));
                v.add(rs2.getString(6));
                v.add(rs2.getString(7));
                v.add(rs2.getString(11));
                v.add(rs2.getString(8));
                df.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {

            DefaultTableModel a = new DefaultTableModel();
            a.setRowCount(0);

            txtinvoid.setText("");
            txtinvocusid.setText("");
            ui2.setText("");
            dtechoserdate.setDate(null);
            lblinvotbltrid.setText("");
            txtinvotblmedid.setText("");
            txtinvotblmedname.setText("");
            lblinvotblstockid.setText("");
//            lblinvotblvolume.setText("");
            lblinvotvluprice.setText("");
            lblinvotblqty.setText("");
            txtinvotblqty.setText("");
            btnadd.setEnabled(true);
            dtechoserdate.setEnabled(true);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtinvotblmedidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinvotblmedidKeyPressed
    }//GEN-LAST:event_txtinvotblmedidKeyPressed

    private void txtinvotblmednameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinvotblmednameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinvotblmednameActionPerformed

    private void txtinvotblmednameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtinvotblmednameFocusGained
        jLabel7.setText("");
        txtinvotblmedname.setText("");
    }//GEN-LAST:event_txtinvotblmednameFocusGained

    private void txtinvotblmednameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinvotblmednameKeyPressed
    }//GEN-LAST:event_txtinvotblmednameKeyPressed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed



        try {
            String hy = txtinvotblqty.getText();
            int yu = Integer.parseInt(hy);
            DefaultTableModel dtm = (DefaultTableModel) tblinvo.getModel();

            Statement s = database.database.pharmacy().createStatement();
            ResultSet rss = s.executeQuery("SELECT * FROM stock WHERE med_id ='" + txtinvotblmedid.getText() + "'");
            if (rss.next()) {
                Vector v = new Vector();
                int qty = rss.getInt(6);
                if (qty > yu && qty >= 5) {

                    v.add(lblinvotbltrid.getText());
                    v.add(txtinvotblmedid.getText());
                    v.add(txtinvotblmedname.getText());
                    v.add(lblinvotblstockid.getText());

                    v.add(lblinvotvluprice.getText());
                    v.add(txtinvotblqty.getText());
                    double d = Double.parseDouble(lblinvotvluprice.getText());
                    double e = Double.parseDouble(txtinvotblqty.getText());
                    double f = d * e;
                    double g = Double.parseDouble(jTextField1.getText());
                    double h = f - ((f * g) / 100);
                    v.add(h);
                    v.add(jTextField1.getText());

                    dtm.addRow(v);
                } else {

                    JOptionPane.showMessageDialog(this, "Sorry, You are exceeding the limit");
                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }



        try {

            lbltot.setText("");

            DefaultTableModel dtm = (DefaultTableModel) tblinvo.getModel();
            int a = tblinvo.getRowCount();
            for (int b = 0; b < a; b++) {
                int c = Integer.parseInt(dtm.getValueAt(b, 7).toString());
                int[] in = new int[]{c};
                for (int k = 0; k < in.length; k++) {
                    int op = in[k];

                    vl = vl + op;
                }

            }
            lbltot.setText(vl + "");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnaddActionPerformed
    int vl;

    private void invoauto() {

        try {

            Statement s = database.database.pharmacy().createStatement();
            ResultSet rs = s.executeQuery("SELECT MAX(inv_id) FROM invoice");
            while (rs.next()) {
                int i = 0;
                i = rs.getInt("MAX(inv_id)");
                txtinvoid.setText(++i + "");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void invotridauto() {
        try {
            Statement s = database.database.pharmacy().createStatement();

            ResultSet rs = s.executeQuery("SELECT MAX(transid) FROM trans");
            while (rs.next()) {
                int i = 0;
                i = rs.getInt("MAX(transid)");

                lblinvotbltrid.setText(++i + "");


            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }
    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        try {
            DefaultTableModel dtm = (DefaultTableModel) tblinvo.getModel();
            for (int i = 0; i < dtm.getRowCount(); i++) {
                String invoiceid = txtinvoid.getText();
                String medid = dtm.getValueAt(i, 1).toString();
                String name = dtm.getValueAt(i, 2).toString();
                String stockid = dtm.getValueAt(i, 3).toString();
                String disc = dtm.getValueAt(i, 7).toString();
                String unitprice = dtm.getValueAt(i, 4).toString();
                String qty = dtm.getValueAt(i, 5).toString();
                String amo = dtm.getValueAt(i, 6).toString();

                cashout();

                database.database.pharmacy().createStatement().executeUpdate("insert into trans (inv_id,med_id,name,stock_id,discount,unitpr,qty,amount) values('" + invoiceid + "','" + medid + "','" + name + "','" + stockid + "','" + disc + "','" + unitprice + "','" + qty + "','" + amo + "')");

                DefaultTableModel dtm1 = (DefaultTableModel) tblinvo.getModel();
                for (int o = 0; o < tblinvo.getRowCount(); o++) {

                    double amount = Double.parseDouble(dtm1.getValueAt(o, 6).toString());
                    double discount = Double.parseDouble(dtm1.getValueAt(o, 7).toString());
                    double subtot = amount - (amount * discount / 100);
                    System.out.println(subtot);
                }

            }
        } catch (Exception e) {
            e.printStackTrace();

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnprintActionPerformed
    public void cashout() {

        try {

            Statement s = database.database.pharmacy().createStatement();
            DefaultTableModel dtm = (DefaultTableModel) tblinvo.getModel();

            int rcnt = dtm.getRowCount();
            int y;
            for (y = 0; y < rcnt; y++) {
                int id = Integer.parseInt(dtm.getValueAt(y, 1).toString());
                int qty = Integer.parseInt(dtm.getValueAt(y, 5).toString());

                s.executeUpdate("UPDATE stock SET quantity=quantity-'" + qty + "' WHERE med_id='" + id + "'");
            }



        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    private void paActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paActionPerformed
        try {

            double i = Double.parseDouble(jLabel9.getText());
            double k = Double.parseDouble(pa.getText());
            double op = k - i;
            DecimalFormat decimalFormat = new DecimalFormat("0.00");
            String s = decimalFormat.format(op);
            bal.setText(s);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_paActionPerformed

    private void paKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paKeyReleased
    }//GEN-LAST:event_paKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            pa.setText("2000");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            pa.setText("1000");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {

            pa.setText("500");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {

            pa.setText("5000");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        try {
            double discount = Double.parseDouble(c2.getText());
            double amount = Double.parseDouble(lbltot.getText());
            double d = amount - (amount * discount / 100);
            DecimalFormat decimalFormat = new DecimalFormat("0.00");
            String s = decimalFormat.format(d);
            jLabel9.setText(s);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_c2ActionPerformed

    private void txtinvotblmedidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinvotblmedidActionPerformed
        try {
//        
            ResultSet rs = database.database.pharmacy().createStatement().executeQuery("SELECT * FROM stock where med_id='" + txtinvotblmedid.getText() + "'");
            while (rs.next()) {
                // txtinvotblmedname.setText(rs.getString("name"));
                //   lblinvotblvolume.setText(rs.getString("volume"));
                // lblinvotvluprice.setText(rs.getString("sel_pr"));
                lblinvotblqty.setText(rs.getString("quantity"));
                lblinvotblstockid.setText(rs.getString("stock_id"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            ResultSet rs = database.database.pharmacy().createStatement().executeQuery("SELECT * FROM medicine where med_id='" + txtinvotblmedid.getText() + "'");
            while (rs.next()) {
                txtinvotblmedname.setText(rs.getString("name"));
                //  lblinvotblvolume.setText(rs.getString("volume"));
                lblinvotvluprice.setText(rs.getString("sel_pr"));
                //lblinvotblqty.setText(rs.getString("quantity"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        txtinvotblqty.requestFocus();
// TODO add your handling code here:
    }//GEN-LAST:event_txtinvotblmedidActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        try {

            salary sa = new salary();
            sa.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void btnaddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddMouseEntered
        btnadd.setCursor(new Cursor(HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddMouseEntered

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed

    private void txtinvotblqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinvotblqtyActionPerformed

        jTextField1.setText("0");
        jTextField1.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_txtinvotblqtyActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed


        btnadd.requestFocus();        // TODO add your handling code here:
        try {
            String hy = txtinvotblqty.getText();
            int yu = Integer.parseInt(hy);
            DefaultTableModel dtm = (DefaultTableModel) tblinvo.getModel();

            Statement s = database.database.pharmacy().createStatement();
            ResultSet rss = s.executeQuery("SELECT * FROM stock WHERE med_id ='" + txtinvotblmedid.getText() + "'");
            if (rss.next()) {
                Vector v = new Vector();
                int qty = rss.getInt(6);
                if (qty > yu && qty >= 5) {

                    v.add(lblinvotbltrid.getText());
                    v.add(txtinvotblmedid.getText());
                    v.add(txtinvotblmedname.getText());
                    v.add(lblinvotblstockid.getText());
//                    v.add(lblinvotblvolume.getText());
                    v.add(lblinvotvluprice.getText());
                    v.add(txtinvotblqty.getText());
                    double d = Double.parseDouble(lblinvotvluprice.getText());
                    double e = Double.parseDouble(txtinvotblqty.getText());
                    double f = d * e;
                    double g = Double.parseDouble(jTextField1.getText());
                    double h = f - ((f * g) / 100);
                    v.add(h);
                    v.add(jTextField1.getText());

                    dtm.addRow(v);
                } else {

                    JOptionPane.showMessageDialog(this, "Sorry, You are exceeding the limit");
                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        try {

//            lbltot.setText("");
//
//            DefaultTableModel dtm = (DefaultTableModel) tblinvo.getModel();
//            int a = tblinvo.getRowCount();
//            for (int b = 0; b < a; b++) {
//                int c = Integer.parseInt(dtm.getValueAt(b, 7).toString());
//                int[] in = new int[]{c};
//                for (int k = 0; k < in.length; k++) {
//                    int op = in[k];
//
//                    vl = vl + op;
//                }
//
//            }
//            lbltot.setText(vl + "");
            DefaultTableModel dtm1 = (DefaultTableModel) tblinvo.getModel();
            double tot = 0;
            double subtot = 0;
            for (int i = 0; i < tblinvo.getRowCount(); i++) {


                double amount = Double.parseDouble(dtm1.getValueAt(i, 6).toString());
                subtot += amount;



            }
            tot = subtot;
            DecimalFormat df1 = new DecimalFormat("0.00");
            String s1 = df1.format(tot);
            lbltot.setText(s1);

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            double amount = Double.parseDouble(lbltot.getText());
            double discount = Double.parseDouble(c2.getText());
            double nettot = amount - (amount * discount / 100);
            DecimalFormat df = new DecimalFormat("0.00");
            String s = df.format(nettot);
            jLabel9.setText(s);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtinvoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinvoidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinvoidActionPerformed

    private void txtinvocusidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinvocusidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinvocusidActionPerformed
    int memo;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//         try {
//            UIManager.setLookAndFeel(new SubstanceBusinessBlueSteelLookAndFeel());
//        } catch (Exception e) {
//            e.printStackTrace();
//        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnprint;
    private javax.swing.JTextField c2;
    private javax.swing.JLabel c3;
    private javax.swing.JButton decpoint;
    private javax.swing.JTextField display1;
    private javax.swing.JTextField display2;
    private javax.swing.JButton divide;
    private com.toedter.calendar.JDateChooser dtechoserdate;
    private javax.swing.JButton eight;
    private javax.swing.JButton equals;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblinvotblqty;
    private javax.swing.JLabel lblinvotblstockid;
    private javax.swing.JLabel lblinvotbltrid;
    private javax.swing.JLabel lblinvotvluprice;
    private javax.swing.JLabel lbltot;
    private javax.swing.JButton multiply;
    private javax.swing.JButton negate;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JTextField pa;
    private javax.swing.JButton reset;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton subtract;
    private javax.swing.JTable tblinvo;
    private javax.swing.JButton three;
    private javax.swing.JLabel time;
    private javax.swing.JButton two;
    private javax.swing.JTextField txtdis;
    private javax.swing.JTextField txtinvocusid;
    private javax.swing.JTextField txtinvoid;
    private javax.swing.JTextField txtinvotblmedid;
    private javax.swing.JTextField txtinvotblmedname;
    private javax.swing.JTextField txtinvotblqty;
    private javax.swing.JLabel ui1;
    private javax.swing.JLabel ui2;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables

    public void DateTimes() {

        try {

            new Thread(new Runnable() {
                public void run() {

                    while (true) {
                        // SimpleDateFormat sdf1 = new SimpleDateFormat("dd/MM/yyyy");
                        SimpleDateFormat sdf2 = new SimpleDateFormat("hh:mm:ss");
                        SimpleDateFormat sdf3 = new SimpleDateFormat("a");

                        //Date d1 = new Date();
                        Date d2 = new Date();
                        Date d3 = new Date();
                        // String s1 = sdf1.format(d1);
                        String s2 = sdf2.format(d2);
                        String s3 = sdf3.format(d3);


                        time.setText(s2 + "" + s3);
                        // date.setText(s1);
                        //txtdate.setText(s1);
                    }

                }
            }).start();

        } catch (Exception e) {
            e.printStackTrace();
        }



    }
}
