/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dilshan
 */
public class med extends javax.swing.JFrame {

    /**
     * Creates new form med
     */
    public med() {
        initComponents();
        jPanel1.setVisible(false);
        auto();

        try {

            Statement s = database.database.pharmacy().createStatement();
            DefaultTableModel dtm = (DefaultTableModel) tblmedicine.getModel();
            dtm.setRowCount(0);

            ResultSet rs = s.executeQuery("SELECT * FROM medicine");

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                //v.add(rs.getString(7));

                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmedicine = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        txtadmedid = new javax.swing.JTextField();
        cmboadmedtype = new javax.swing.JComboBox();
        txtadmedbprice = new javax.swing.JTextField();
        txtadmedsprice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtadmedmfgname = new javax.swing.JTextField();
        txtadmedname = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Medicine Index");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblmedicine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine ID", "Medicine Name", "Type", "Buying Price", "Selling Price", "Mfg. Name"
            }
        ));
        jScrollPane1.setViewportView(tblmedicine);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 382, 778, 194));

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, 40));

        txtadmedid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtadmedidKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtadmedidKeyTyped(evt);
            }
        });
        getContentPane().add(txtadmedid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 11, 300, 31));

        cmboadmedtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pills", "Syrups", "Cream" }));
        cmboadmedtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboadmedtypeActionPerformed(evt);
            }
        });
        getContentPane().add(cmboadmedtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 113, 300, 33));
        getContentPane().add(txtadmedbprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 300, 27));
        getContentPane().add(txtadmedsprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 300, 32));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Medicine ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 100, 26));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Medicine Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 26));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Type:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 114, 100, 26));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Buying Price:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 26));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Selling Price:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, 26));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Mfg. Name:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, 26));
        getContentPane().add(txtadmedmfgname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 300, 27));

        txtadmedname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtadmednameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtadmednameKeyTyped(evt);
            }
        });
        getContentPane().add(txtadmedname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 62, 300, 33));

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 164, 137, 28));

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 12, 137, 28));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 362, 798, -1));

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 587, 137, 28));

        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 64, 137, 28));

        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 115, 137, 28));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        home gt=new home();
       gt.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            txtadmedid.setText("");
            txtadmedname.setText("");
            cmboadmedtype.setSelectedIndex(0);
           // cmboadmedvolume.setSelectedIndex(0);
            txtadmedbprice.setText("");
            txtadmedsprice.setText("");
            txtadmedmfgname.setText("");

            auto();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {

            int a = Integer.parseInt(txtadmedbprice.getText());
            int b = Integer.parseInt(txtadmedsprice.getText());
            int c = Integer.parseInt(txtadmedid.getText());
            String hh=cmboadmedtype.getSelectedItem().toString();

            DefaultTableModel dtm = (DefaultTableModel) tblmedicine.getModel();
            Vector v = new Vector();
            v.add(c);
            v.add(txtadmedname.getText());
            v.add(cmboadmedtype.getSelectedItem());
           // v.add(cmboadmedvolume.getSelectedItem().toString());
            v.add(a);
            v.add(b);
            v.add(txtadmedmfgname.getText());
            dtm.addRow(v);

            Statement s = database.database.pharmacy().createStatement();
            s.executeUpdate("INSERT INTO medicine VALUES('" + c + "','" + txtadmedname.getText() + "','" + hh + "','" + a + "','" + b + "','" + txtadmedmfgname.getText() + "')");
            // s.executeUpdate("INSERT INTO type VALUES('"+c+"','"+cmboadmedtype.getSelectedItem()+"','"+cmboadmedvolume.getSelectedItem()+"')");


        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {

            Statement s = database.database.pharmacy().createStatement();
            s.executeUpdate("DELETE FROM medicine WHERE med_id='" + txtadmedid.getText() + "'");


        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {

            int a = Integer.parseInt(txtadmedbprice.getText());
            int b = Integer.parseInt(txtadmedsprice.getText());
            int c = Integer.parseInt(txtadmedid.getText());

            Statement s = database.database.pharmacy().createStatement();
            s.executeUpdate("UPDATE medicine SET name='" + txtadmedname.getText() + "',type='" + cmboadmedtype.getSelectedItem().toString() + "',buy_pr='" + a + "', sel_pr='" + b + "',mfg_name='" + txtadmedmfgname.getText() + "' WHERE med_id='" + c + "'");




        } catch (Exception e) {
            e.printStackTrace();
        }

        try {

            Statement s = database.database.pharmacy().createStatement();
            DefaultTableModel dtm = (DefaultTableModel) tblmedicine.getModel();
            dtm.setRowCount(0);

            ResultSet rs = s.executeQuery("SELECT * FROM medicine");

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));

                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtadmedidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtadmedidKeyTyped
//        try {
//             Statement s = database.database.pharmacy().createStatement();
//             
//            
//            ResultSet rs = s.executeQuery("SELECT * FROM medicine WHERE med_id LIKE'" + txtadmedid.getText() + "%'");
//            while (rs.next()) {
//                txtadmedname.setText(rs.getString(2));
//                cmboadmedtype.setSelectedItem(rs.getString(3));
//                cmboadmedvolume.setSelectedItem(rs.getString("volume"));
//                
//                txtadmedbprice.setText(rs.getString(5));
//                txtadmedsprice.setText(rs.getString(6));
//                txtadmedmfgname.setText(rs.getString(7));
//
//            }
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_txtadmedidKeyTyped

    private void txtadmedidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtadmedidKeyPressed
    }//GEN-LAST:event_txtadmedidKeyPressed

    private void cmboadmedtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboadmedtypeActionPerformed
    }//GEN-LAST:event_cmboadmedtypeActionPerformed

    private void txtadmednameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtadmednameKeyTyped

    }//GEN-LAST:event_txtadmednameKeyTyped

    private void txtadmednameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtadmednameKeyReleased
        if (txtadmedname.getText().isEmpty()) {
            jPanel1.setVisible(false);
        } else {
            jPanel1.setVisible(true);
            try {
                Statement s = database.database.pharmacy().createStatement();
                ResultSet rs = s.executeQuery("SELECT * FROM medicine WHERE name LIKE'" + txtadmedname.getText() + "%'");
                Vector v = new Vector();
                if (rs.next()) {
                    v.add(rs.getString("name"));
                } else {
                    jPanel1.setVisible(false);
                }
                jList1.setModel(new DefaultComboBoxModel(v));

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadmednameKeyReleased

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        try {
            Statement s = database.database.pharmacy().createStatement();

            String s1 = jList1.getSelectedValue().toString();
            txtadmedname.setText(s1);
            ResultSet rs = s.executeQuery("SELECT * FROM medicine WHERE name like'" + txtadmedname.getText() + "%'");
            while (rs.next()) {

                txtadmedid.setText(rs.getString(1));
                cmboadmedtype.setSelectedItem(rs.getString(3));
               // cmboadmedvolume.setSelectedItem(rs.getString(4));
                txtadmedbprice.setText(rs.getString(5));
                txtadmedsprice.setText(rs.getString(6));
                txtadmedmfgname.setText(rs.getString(7));

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jList1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new med().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmboadmedtype;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblmedicine;
    private javax.swing.JTextField txtadmedbprice;
    private javax.swing.JTextField txtadmedid;
    private javax.swing.JTextField txtadmedmfgname;
    private javax.swing.JTextField txtadmedname;
    private javax.swing.JTextField txtadmedsprice;
    // End of variables declaration//GEN-END:variables

    private void auto() {
        try {

            Statement s = database.database.pharmacy().createStatement();
            ResultSet rs = s.executeQuery("SELECT MAX(med_id) FROM medicine");
            while (rs.next()) {
                int i = 0;
                i = rs.getByte("MAX(med_id)");

                txtadmedid.setText(++i + "");

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
